name: Build Autoreduction
description: Build Autoreduction in a test environment

runs:
  using: composite

  steps:
    - name: Install Autoreduction
      run: |
        python -m pip install --upgrade pip
        pip install -e .
      shell: bash

    - name: Install test suite dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Configure credentials
      run: autoreduce-creds-migrate
      shell: bash
