name: Build Autoreduction
description: Build Autoreduction in a test environment

runs:
  using: composite

  steps:
    - name: Pull ActiveMQ
      run: docker pull rmohr/activemq
      shell: bash

    - name: Start ActiveMQ
      run: docker run --name activemq -p 61613:61613 -p 8161:8161 -d rmohr/activemq
      shell: bash

    - name: Install Autoreduction
      run: |
        python -m pip install --upgrade pip
        pip install -e .
      shell: bash

    - name: Install test suite dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Configure credentials
      run: autoreduce-creds-migrate
      shell: bash
