name: Tests
on: [push]

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: autoreduction/autoreduce-actions/build@main
        with:
          package_name: autoreduce_utils
          migrate_db: false

      - name: Remote dotenv to Environment (configserver alike)
        uses: Steph0/dotenv-configserver@v1.2.0
        with:
          repository: "autoreduction/autoreduce-workspace"

      - name: Install Tox
        run: python -m pip install tox tox-gh-actions

      - name: Run unit tests
        run: tox -e pytest

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

  dependency-check:
    name: Dependency-Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ job.container.image }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ job.container.image }}-pip-

      - name: Pip install
        run: |
          pip install --upgrade pip
          pip install -e .

  Inspection:
    name: Code Inspection
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: autoreduction/autoreduce-actions/build@main
        with:
          package_name: autoreduce_utils
          migrate_db: false

      - name: Remote dotenv to Environment (configserver alike)
        uses: Steph0/dotenv-configserver@v1.2.0
        with:
          repository: "autoreduction/autoreduce-workspace"

      - name: Install Tox
        run: python -m pip install tox tox-gh-actions

      - name: Run code inspection with tox
        run: tox -e code_inspection
